In [1]:
import numpy as np
import pandas as pd


In [2]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [3]:
arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype

dtype('float64')

In [4]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.shape(arr3)

(3, 3)

In [6]:
df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [7]:
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [8]:
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [9]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [14]:
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7

array([ 0,  7, 14])

In [15]:
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[5, 1, 9],
       [2, 4, 6],
       [8, 3, 1]])

In [17]:
[x for x in range(1, 301, 7)]

[1,
 8,
 15,
 22,
 29,
 36,
 43,
 50,
 57,
 64,
 71,
 78,
 85,
 92,
 99,
 106,
 113,
 120,
 127,
 134,
 141,
 148,
 155,
 162,
 169,
 176,
 183,
 190,
 197,
 204,
 211,
 218,
 225,
 232,
 239,
 246,
 253,
 260,
 267,
 274,
 281,
 288,
 295]

In [18]:
281%10

1

In [19]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [20]:
np.full((5,5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.array([[1,2,3,4,5], [5,1,2,3,4], [4,5,1,2,3], [3,4,5,1,2], [2,3,4,5,1]])

array([[1, 2, 3, 4, 5],
       [5, 1, 2, 3, 4],
       [4, 5, 1, 2, 3],
       [3, 4, 5, 1, 2],
       [2, 3, 4, 5, 1]])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [24]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [25]:
my_array = np.array([x for x in range(10)])
my_array[5]

5

In [26]:
my_array[-1]

9

In [27]:
my_array[3:6]

array([3, 4, 5])

In [28]:
my_array[1:8:3]

array([1, 4, 7])

In [29]:
my_array[[1,2]]

array([1, 2])

In [30]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array[1][2]

12

In [31]:
my_array[1,2]

12

In [32]:
my_array[:,2]

array([ 3, 12, 47])

In [33]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [34]:
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [35]:
sum(big_secret[:,-1])

3154.332495807108

In [36]:
np.shape(big_secret)

(5, 51)

In [37]:
sum(sum(big_secret[:,:5]*np.eye(5)))

121.37188663699624

In [38]:
x=1
for i in (sum(big_secret[:,-5:]*np.eye(5))):
    print(i)

460.0
33.075670817082454
2304.0
33.13608305156178
294.0


In [39]:
x

1

In [40]:
my_array = np.random.randint(1, 100, (4, 6)) 
my_array

array([[85, 99, 47, 59, 83, 11],
       [26, 84, 21, 40,  7, 95],
       [ 1, 44, 36,  2, 79, 45],
       [59, 14, 53, 73, 96, 33]])

In [41]:
my_slice = my_array[1:3, 2:4]
my_slice

array([[21, 40],
       [36,  2]])

In [42]:
my_slice[:] = 0
my_slice

array([[0, 0],
       [0, 0]])

In [43]:
my_array

array([[85, 99, 47, 59, 83, 11],
       [26, 84,  0,  0,  7, 95],
       [ 1, 44,  0,  0, 79, 45],
       [59, 14, 53, 73, 96, 33]])

In [44]:
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [45]:
big_secret[0::2,0::2] = -1
big_secret[1::2,1::2] = 1

In [46]:
big_secret

array([[-1.00000000e+00,  1.00000000e+01, -1.00000000e+00,
         5.60000000e+01, -1.00000000e+00,  2.40000000e+01,
        -1.00000000e+00,  7.00000000e+01, -1.00000000e+00,
         1.40000000e+02, -1.00000000e+00,  6.00000000e+01,
        -1.00000000e+00,  1.30000000e+02, -1.00000000e+00,
         2.24000000e+02, -1.00000000e+00,  9.60000000e+01,
        -1.00000000e+00,  1.90000000e+02, -1.00000000e+00,
         3.08000000e+02, -1.00000000e+00,  1.32000000e+02,
        -1.00000000e+00,  2.50000000e+02, -1.00000000e+00,
         3.92000000e+02, -1.00000000e+00,  1.68000000e+02,
        -1.00000000e+00,  3.10000000e+02, -1.00000000e+00,
         4.76000000e+02, -1.00000000e+00,  2.04000000e+02,
        -1.00000000e+00,  3.70000000e+02, -1.00000000e+00,
         5.60000000e+02, -1.00000000e+00,  2.40000000e+02,
        -1.00000000e+00,  4.30000000e+02, -1.00000000e+00,
         6.44000000e+02, -1.00000000e+00,  2.76000000e+02,
        -1.00000000e+00,  4.90000000e+02, -1.00000000e+0

In [47]:
big_secret[2,2]

-1.0

In [48]:
sum(sum(big_secret[:,:5]*np.eye(5)))

-1.0

In [49]:
sum(sum(big_secret[:,-5:]*np.eye(5)))

-1.0

In [50]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [51]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [52]:
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
my_array = np.random.randint(0, 10, 20)
my_array

array([0, 0, 7, 4, 5, 2, 4, 0, 5, 7, 1, 9, 0, 4, 4, 3, 1, 8, 9, 8])

In [54]:
my_array.reshape((4,5))

array([[0, 0, 7, 4, 5],
       [2, 4, 0, 5, 7],
       [1, 9, 0, 4, 4],
       [3, 1, 8, 9, 8]])

In [55]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [56]:
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [57]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[5, 7, 5, 1],
       [6, 2, 2, 7],
       [4, 0, 9, 2]])

In [58]:
my_array<5

array([[False, False, False,  True],
       [False,  True,  True, False],
       [ True,  True, False,  True]])

In [59]:
my_array[my_array<5]

array([1, 2, 2, 4, 0, 2])

In [60]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[5, 5],
       [6, 2],
       [4, 9]])

In [61]:
my_array

array([[5, 7, 5, 1],
       [6, 2, 2, 7],
       [4, 0, 9, 2]])

In [62]:
my_array = np.random.randint(0, 10, (4, 6))
my_array

array([[4, 4, 5, 9, 4, 6],
       [5, 2, 7, 6, 6, 9],
       [7, 7, 7, 3, 6, 8],
       [6, 3, 8, 7, 0, 8]])

In [63]:
np.sort(my_array, axis=1)

array([[4, 4, 4, 5, 6, 9],
       [2, 5, 6, 6, 7, 9],
       [3, 6, 7, 7, 7, 8],
       [0, 3, 6, 7, 8, 8]])

In [64]:
np.sort(my_array, axis=0)

array([[4, 2, 5, 3, 0, 6],
       [5, 3, 7, 6, 4, 8],
       [6, 4, 7, 7, 6, 8],
       [7, 7, 8, 9, 6, 9]])

In [65]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [69]:
np.cos(great_secret[0]).sum()

0.16006721889793019

In [70]:
sum(np.cos(great_secret[0]))

0.16006721889793019

In [74]:
great_secret[great_secret>50].sum()

5470.0

In [84]:
np.size(great_secret)

300

In [93]:
great_secret.reshape(1,np.size(great_secret))[0,150]

7.0710678118654755

In [96]:
np.sort(great_secret, axis=0)[-1].sum()

115.12148016521353

In [106]:
students=np.array([[1,135,34,4],
                   [2,160,43,5],
                   [3,163,40,4.3],
                   [4,147,44,5],
                   [5,138,41,4.7],
                   [6,149,54,3.9],
                   [7,136,39,4.2],
                   [8,154,48,4.9],
                   [9,137,35,3.7],
                   [10,165,60,4.6]])

In [107]:
mean = np.mean(students[:,-1])
mean

4.430000000000001

In [109]:
median = np.median(students[:,-1])
median

4.449999999999999

In [110]:
sort = np.sort(students[:,-1])
(sort[4]+sort[5])/2

4.449999999999999

In [111]:
np.median(students[:,2])

42.0

In [113]:
np.mean(students[:,2])-np.median(students[:,2])

1.7999999999999972

In [114]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [115]:
np.corrcoef(students[:,1], students[:,3]) #height and marks

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

In [117]:
np.corrcoef(students[:,2], students[:,3]) #weight and marks

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [120]:
std = np.std(students[:,1]) #std of heights
std

11.083320801997928

In [121]:
np.std(students[:,3])

0.4517742799230607

In [125]:
np.std(students[:,2])**2  # std**2=dispersion

60.36

In [127]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [131]:
my_array[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [136]:
my_sin = np.sin(my_array)
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [137]:
my_sin.sum()

-0.05812430261413351

In [141]:
my_sin[1:4,1:4] = np.ones((3,3))
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [143]:
my_sin.sum()

7.571718421269144

In [149]:
my_sin[:,0:4].reshape(10,2)[:,0].sum()

2.4057172058139544

In [158]:
bigdata = np.array([x**2 for x in range(100, 1001) if x%2])

In [161]:
np.median(bigdata)

302501.0

In [162]:
np.std(bigdata)

292095.0301991155

In [170]:
np.corrcoef(bigdata[0::2], bigdata[1::2])

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])