In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],
              [-3,1],
              [1,2],
              [1,-1]])
A

array([[ 1,  2],
       [-3,  1],
       [ 1,  2],
       [ 1, -1]])

In [6]:
b = np.array([[1],
              [4],
              [5],
              [0]])
b

array([[1],
       [4],
       [5],
       [0]])

In [4]:
G = A.T@A
G

array([[12,  0],
       [ 0, 10]])

In [5]:
np.linalg.inv(G)

array([[0.08333333, 0.        ],
       [0.        , 0.1       ]])

In [7]:
np.linalg.inv(G)@(A.T@b)

array([[-0.5],
       [ 1.6]])

In [9]:
-29.3-0.26*0.2+8.4*6

21.048000000000005

In [10]:
A = np.array([[-0.535, 0.707],
              [-0.267, -0.707],
              [0.802, 0]])
A

array([[-0.535,  0.707],
       [-0.267, -0.707],
       [ 0.802,  0.   ]])

In [11]:
A.T@A

array([[ 1.000718, -0.189476],
       [-0.189476,  0.999698]])