In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes
import numpy as np
import pickle

X, y = load_diabetes(return_X_y=True)
X = X[:, 0].reshape(-1, 1) # Берём только один признак
regressor = LinearRegression()
regressor.fit(X,y)

LinearRegression()

In [3]:
value_to_predict = np.array([0.04]).reshape(-1, 1)
regressor.predict(value_to_predict)

array([164.30080714])

In [4]:
with open('myfile.pkl', 'wb') as output:
    pickle.dump(regressor, output) #Сохраняем

with open('myfile.pkl', 'rb') as pkl_file:
    regressor_from_file = pickle.load(pkl_file) #Загружаем

In [5]:
regressor_from_file.predict(value_to_predict)

array([164.30080714])

In [6]:
value_to_predict = np.array([0]).reshape(-1, 1)

In [7]:
regressor_from_file.predict(value_to_predict)

array([152.13348416])